Logger/Controllers/StatController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logger.Core.Models;

using Logger.ViewModels;
using MvcPaging;

namespace Logger.Controllers
{
    public class StatController : BaseController
    {
        const int DefaultPageSize = 10;

        [Authorize]
        public ActionResult Index(int? page)
        {
            int siteid = 0;
            if (Session["siteid"] == null || !Int32.TryParse(Session["siteid"].ToString(), out siteid))
            {
                var action = Url.Action("Index");
                if (action != null)
                    return RedirectToAction("Index", "Site",
                        new {urlreferrer = action.ToString(CultureInfo.InvariantCulture)});
            }


            var pageSizeStr = Request.Cookies["isepam_stats_pagesize"];
            int pageSize = DefaultPageSize;
            if (pageSizeStr == null || !Int32.TryParse(pageSizeStr.Value, out pageSize))
            {
                var myCookie = new HttpCookie("isepam_stats_pagesize");
                myCookie.Value = DefaultPageSize.ToString(CultureInfo.InvariantCulture);
                myCookie.Expires = DateTime.Now.AddYears(1);
                Response.Cookies.Add(myCookie);
            }

            var currentPageIndex = page.HasValue ? page.Value - 1 : 0;

            return View(ErrorRepository.GetAll(SiteRepository.Get(siteid).ApiKey)
                .Select(item => new ExceptionModel{Browser = item.Browser,BrowserId = item.BrowserId,DateTime = item.DateTime,Id=item.Id,Message = item.Message,Name = item.Name,OsId = item.OsId,OS = item.OS})
                .ToPagedList(currentPageIndex, pageSize));
        }

        [Authorize]
        public ActionResult ErrorDetail(int? id)
        {
            int siteid = 0;
            if (Session["siteid"] == null || !Int32.TryParse(Session["siteid"].ToString(), out siteid))
            {
                var action = Url.Action("Index");
                if (action != null)
                    return RedirectToAction("Index", "Site",
                        new { urlreferrer = action.ToString(CultureInfo.InvariantCulture) });
            }

            var site = SiteRepository.Get(siteid);
            var apikey = site==null ? string.Empty : site.ApiKey;

            if (id == null) id = 0;

            var error = ErrorRepository.Get(apikey, (Int32)id);
            if (error == null)
                ViewBag.NullId = id;
            var next = ErrorRepository.GetNext(apikey, id.Value);
            var prev = ErrorRepository.GetPrev(apikey, id.Value);
            if (Request.IsAjaxRequest())
                return PartialView("ErrorDetailTbl",
                                   new FailWithPager(error, prev == null ? 0 : prev.Id, next == null ? 0 : next.Id));
            return View(new FailWithPager(error, prev == null ? 0 : prev.Id, next == null ? 0 : next.Id));
        }
    }
}

Logger/Views/Stat/ErrorDetail.cshtml
@model Logger.Core.Models.FailWithPager
@{
    ViewBag.Title = "ErrorDetail #" + @Model.Error.Id;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="clearfix">
    <div class="pull-left">
        <h3>Exception detail</h3>
    </div>
    <form class="navbar-form pull-right col-xs-3" role="search" onsubmit="errorShow($('#iderror').val()); return false;">
        <div class="input-group">
            <input id="iderror" type="text" class="form-control" placeholder="enter id error" autofocus onkeyup=" this.value = this.value.replace(/\D/, '') ">
            <div class="input-group-btn">
                <button onclick=" errorShow($('#iderror').val()); " type="button" class="btn btn-success"><span class="glyphicon glyphicon-search"></span></button>
            </div>
        </div>
    </form>
</div>

<div id="errordetailcontainer">
    @Html.Partial("ErrorDetailTbl", Model)
</div>

<script type="text/javascript">
    $(document).bind('keyup', function(event) {
        if (event.keyCode == '39') { //button "VK_RIGHT"
            if (!$('#nexterror').hasClass("disabled")) {
                errorShow($('#nexterror').attr("errid"));
            }
        }
        if (event.keyCode == '37') { //button "VK_LEFT"
            if (!$('#preverror').hasClass("disabled")) {
                errorShow($('#preverror').attr("errid"));
            }
        }
    });
</script>

@section scripts {
    @Scripts.Render("~/Scripts/jquery.history")
    @Scripts.Render("~/Scripts/Prettify/run_prettify")
    @Scripts.Render("~/Scripts/app/logger-site")
}

Logger/Views/Stat/ErrorDetailTbl.cshtml
@using System.Diagnostics
@model Logger.Core.Models.FailWithPager

@if (Model.Error == null)
{
    <h4><span class="label label-info">Important</span> Exception #@ViewBag.NullId doesn't exist!</h4> 
}
else
{
    <table id="errordetail" class="table table-bordered">
        <tbody>
            <tr>
                <td class="curid">Error ID:</td>
                <td><b>@Model.Error.Id</b></td>
            </tr>
            <tr>
                <td>Error name:</td>
                <td><b>@Model.Error.Name</b></td>
            </tr>
            <tr>
                <td>Datetime:</td>
                <td><b>@Model.Error.DateTime</b></td>
            </tr>
            <tr>
                <td>Message:</td>
                <td class="curmessage"><b>@Model.Error.Message</b></td>
            </tr>
            <tr>
                <td>OS & Browser:</td>
                <td><b>@Model.Error.OS.Name & @Model.Error.Browser.Name</b></td>
            </tr>
            <tr>
                <td>Referrer:</td>
                <td><a href="@Model.Error.Referrer">@Model.Error.Referrer</a></td>
            </tr>
            <tr>
                <td>Useragent:</td>
                <td class="curuseragent">@Model.Error.Useragent</td>
            </tr>
            <tr>
                <td>Postdata:</td>
                <td>@Model.Error.Postdata</td>
            </tr>
            <tr>
                <td>Targetsite:</td>
                <td class="curtargetsite">@Model.Error.TargetSite</td>
            </tr>
            <tr>
                <td>Source:</td>
                <td>@Model.Error.Source</td>
            </tr>

            <tr>
                <td>Stacktrace:</td>
                <td class="curstacktrace">
                   <pre class="prettyprint">@(new HtmlString(Model.Error.StackTrace.Replace("\n", "")))</pre>
                </td>
            </tr>
        </tbody>
    </table>
}
<ul class="pager">
    <li id="preverror" 
        @{
            Debug.Assert(@Model != null, "@Model != null");
        }
        @if(Model.Prev==0){<text>class="disabled"</text>}else{<text>errid="@Model.Prev"</text>}>
        <a href="#" @if(@Model.Prev!=0){<text>onclick="javascript:errorShow(@Model.Prev); "</text>}>Previous</a>
    </li>
    <li id="nexterror" style="margin: 0 0 0 20px;"@if(@Model.Next==0){<text>class="disabled"</text>}else{<text>errid="@Model.Next"</text>}>
        <a href="#" @if(Model.Next!=0){<text>onclick="javascript:errorShow(@Model.Next); "</text>}>Next</a>
    </li>
</ul>

Logger/Views/Stat/Index.cshtml
@using Logger.ViewModels
@model IPagedList<ExceptionModel>
@{
    ViewBag.Title = "Exceptions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="pull-left">
        <h3>General Statistics</h3>
    </div>
    <div class="btn-group pull-right" style="margin-top: 20px;">
        <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown">
            <div id="pagesize"></div> <span class="caret"></span>
        </button>

        <ul class="dropdown-menu">
            <li><a href="javascript:changepagesize(10);">10</a></li>
            <li><a href="javascript:changepagesize(25);">25</a></li>
            <li><a href="javascript:changepagesize(50);">50</a></li>
            <li><a href="javascript:changepagesize(100);">100</a></li>
        </ul>
    </div>
    <div class="clearfix"></div>
</div>
<table width="100" id="maintbl" class="table table-bordered">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Date & time
            </th>
            <th>
                Exception's message
            </th>
            <th>
                OS
            </th>
            <th>
                Browser
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (ExceptionModel error in Model)
        {
            <tr>
                <td class="namecss">@error.Name</td>
                <td class="dtcss">@error.DateTime</td>
                <td class="messagecss pointer" title="@error.Message" onclick=" location.href = '@Url.Action("ErrorDetail", "Stat", new {id = error.Id})' ">@error.Message</td>
                <td class="oscss">
                    @{
                        if (error.OS.Name.StartsWith("Win"))
                        {
                            <img src='@Url.Content("~/Content/imgs/win.png")' alt="WinNT" height="35" width="35" />
                        }
                        else
                        {
                            switch (error.OS.Name)
                            {
                                case "Unix":
                                    <img src='@Url.Content("~/Content/imgs/unix.png")' alt="Unix" height="35" width="35" />
                                    break;
                                case "Mac":
                                    <img src='@Url.Content("~/Content/imgs/mac.png")' alt="Mac" height="35" width="35" />
                                    break;
                                case "Linux":
                                    <img src='@Url.Content("~/Content/imgs/unix.png")' alt="Linux" height="35" width="35" />
                                    break;
                                default:
                                    Html.DisplayText("Unknown operation system");
                                    break;
                            }
                        }
                    }
                </td>
                <td class="browsercss">
                    @{
                        switch (error.Browser.Name)
                        {
                            case "Chrome":
                                <img src='@Url.Content("~/Content/imgs/chrome.png")' alt="Chrome" height="35" width="35" />
                                break;
                            case "IE":
                                <img src='@Url.Content("~/Content/imgs/ie.png")' alt="IE" height="35" width="35" />
                                break;
                            case "Safari":
                                <img src='@Url.Content("~/Content/imgs/safari.png")' alt="Safari" height="35" width="35" />
                                break;
                            case "Opera":
                                <img src='@Url.Content("~/Content/imgs/opera.png")' alt="Opera" height="35" width="35" />
                                break;
                            case "Firefox":
                                <img src='@Url.Content("~/Content/imgs/firefox.png")' alt="Firefox" height="35" width="35" />
                                break;
                            default:
                                <img src='@Url.Content("~/Content/imgs/unknown.png")' alt="Unknown" height="35" width="35" />
                                break;
                        }
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount).Options(o => o.DisplayTemplate("BootstrapPagination"))

@section scripts {
    @Scripts.Render("~/Scripts/app/logger-site")
    @Scripts.Render("~/Scripts/cookie")
    @*<script src="/Scripts/jquery.cookie.js"></script>*@

    <script type="text/javascript">
        $(document).ready(function() {
            var pagesize = $.cookie('isepam_stats_pagesize');
            if (pagesize == undefined) {
                $.cookie('isepam_stats_pagesize', '10', { expires: 365 });
                pagesize = 10;
            }
            $('#pagesize').html(pagesize);
        });
    </script>
}